// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// ──────────────────────────────────────────────────────────────────────────────
// ARQUITECTURA MULTI-TENANT
//
// Este proyecto usa DOS esquemas de Prisma:
//
//  1. prisma/schema.prisma   → Esquema POR TENANT (BD propia de cada entidad)
//     - Se migra una vez por cada nueva BD creada para un tenant
//     - DATABASE_URL apunta a la BD del tenant en desarrollo
//
//  2. prisma/meta/schema.prisma → META-BD (BD central de la plataforma)
//     - Registra todos los tenants: dominios, connection strings, planes, etc.
//     - META_DATABASE_URL apunta a esta BD única global
//
// Comandos:
//   Tenant (dev):  npx prisma migrate dev --config prisma.config.ts
//   Meta:          npx prisma migrate dev --config prisma.config.meta.ts
// ──────────────────────────────────────────────────────────────────────────────

export default defineConfig({
  // Esquema por-tenant (aplica a la BD del tenant de desarrollo)
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
